name: create build and deployment data

on:
  release:
    types: [published]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: echo Creating build and deployment data
